### ISSUE TITLE
documentation for bootstrap/main.tsx?

### ISSUE THREAD

**Issue by scottrblock** [pengx17/logseq-plugin-template-react#352]
Hello,

Thanks so much for this template, super helpful. I'm trying to wrap my head around the difference between `bootstrap.tsx` and `main.tsx`. I'm not sure why there are both, and if/how to combine them. They seem redundant, so I would like to remove one if possible.

**Comment by pengx17** [comment]
Ops, good catch! TBH I cannot remember why I add `bootstrap.tsx` with `main.tsx` ... You can file a PR to remove `bootstrap.tsx` if you want :D

**Comment by pengx17** [comment]
Should have been fixed by https://github.com/pengx17/logseq-plugin-template-react/commit/737ea4fd0da894f06b7b1a982d9decb82a186f02

**Comment by scottrblock** [comment]
Awesome, thanks @pengx17. I ended up making my own similar template because I wanted to use preact (https://github.com/phonetonote/ptn-logseq-starter), but this served as a very helpful guide!
