### ISSUE TITLE
TailwindCSS doesn't work

### ISSUE THREAD

**Issue by KKKIIO** [pengx17/logseq-plugin-template-react#422]
Thanks so much for this template. I'm kind of a newbie to Logseq Plugin Development and Frontend Stack. I try to use TailwindCSS, but it doesn't work. And I try inline styling, which works as expect.

```jsx
<div className="border-red-500" style={{ color: "red" }}>{should}</div>
```

I update the plugin as follows:
1. Edit & Save code
2. Run `pnpm run build`
3. Click the "Reload" button in Logseq Plugins dialog.

Is there anything I miss?

**Comment by pengx17** [comment]
I think the issue related to border coloring in tailwind is that this `div` should also have a `border` in addition to the border color to make it work. You can try this instead:
```
<div className="border border-red-500">{should}</div>
```

**Comment by KKKIIO** [comment]
@pengx17 Thanks for the help! I should try those class at playground first. But I still get some wire results:
1. `border` will take effect but not `border-2`
2. `font-bold` will take effect but not `font-extrabold`

```html
<div class="grid grid-cols-2 gap-4">
  <div class="border-2 border-red-500 text-green-500 font-extrabold">DO</div>
  <div class="border-2 border-red-500 text-green-500 font-extrabold">SCHEDULE</div>
  <div class="border-2 border-red-500 text-green-500 font-extrabold">DELEGATE</div>
  <div class="border-2 border-red-500 text-green-500 font-extrabold">ELIMINATE</div>
</div>
```
I tried these code in tailwind playground and got some expect result:
![playground](https://user-images.githubusercontent.com/12840157/191062903-56537be5-3226-46c3-99a5-3524ecf14055.png)
But in Logseq it just doesn't work.
![logseq](https://user-images.githubusercontent.com/12840157/191063257-7d9e39a6-2b2a-40ce-9aa2-68adf4748aac.png)
Below is the code I run in `logseq.App.onMacroRendererSlotted` callback:
```tsx
const html: string = ReactDOMServer.renderToStaticMarkup(
  <App />
)
logseq.provideUI({
  key: `uic-${slot}`,
  slot,
  reset: true,
  template: html,
})
```

**Comment by pengx17** [comment]
When using tailwind class names, it will also generate a CSS file. Normally this CSS file will be loaded automatically to the current HTML file. By default the CSS file will be loaded via iframe in Logseq's implementation. But when rendering using `onMacroRendererSlotted`, the CSS file will not be loaded at all.
BTW I am not recommending using Tailwind if you are aiming to write a Logseq macro plugin. I recommended you to use inline styles this time if you are not too familiar with how Logseq loads plugins

**Comment by KKKIIO** [comment]
Thank you very much for the patient explanation!
